# Generated by Django 5.0.3 on 2025-01-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('collage_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=50)),
                ('cwebsite', models.CharField(max_length=50, unique=True)),
                ('cAddress', models.CharField(max_length=100)),
                ('cAffiliation', models.CharField(max_length=50)),
                ('cabout', models.TextField()),
            ],
        ),
    ]
