# Generated by Django 5.0.3 on 2025-01-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('sName', models.CharField(max_length=50)),
                ('sEmail', models.CharField(max_length=50, unique=True)),
                ('sAddress', models.CharField(max_length=100)),
                ('sCourse', models.CharField(max_length=50)),
                ('shighestqualification', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation')], max_length=15)),
            ],
        ),
    ]
