# Generated by Django 5.0.3 on 2025-01-12 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='collage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.collage'),
        ),
    ]
