# Generated by Django 5.0.3 on 2025-01-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_collage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shighestqualification',
            field=models.CharField(max_length=15),
        ),
    ]
